### ISSUE TITLE
Ver 0.1.5 nanosite build crashes with keyerror

### ISSUE THREAD

**Issue by janezdu** [qema/nanosite#2]
The error report I get is this:

``` shell
D:\cs\zdpage> nanosite build
Traceback (most recent call last):
  File "D:\Chtuff\python\Scripts\nanosite-script.py", line 9, in <module>
    load_entry_point('nanosite==0.1.5', 'console_scripts', 'nanosite')()
  File "d:\chtuff\python\lib\site-packages\nanosite\__init__.py", line 98, in main
    build.make_site(args.site_dir, ctx)
  File "d:\chtuff\python\lib\site-packages\nanosite\build.py", line 206, in make_site
    templates.fill_template(templates.get_template(master_tmpl_path), ctx)
  File "d:\chtuff\python\lib\site-packages\nanosite\templates.py", line 209, in fill_template
    val = str(ctx_fetch(ctx, key[1:].strip()))
  File "d:\chtuff\python\lib\site-packages\nanosite\templates.py", line 25, in ctx_fetch
    value = value(ctx, *tokenize_params(ctx, params))
  File "<string>", line 53, in make_menu
  File "<string>", line 42, in make_menu
KeyError: 'site'
```

where zdpage is where I had originally set up the nanosite. I downgraded back to 0.1.3 and it built again.

**Comment by qema** [comment]
Some naming updates in 0.1.5. Replace all references to `is_file` by `isFile`. Or import the newest version of the packages: `nanosite import xx --force`.
